### ISSUE TITLE
Add websocket or rabbit mq topic to support parsing logs easily

### ISSUE THREAD

**Issue by sergiors** [sergiors/coffeeheim#2]
Test mosquitto as MQTT protocol
```
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data/
    restart: unless-stopped
    user: 1000:1000
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN
    depends_on:
      - mosquitto
```
